# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c969dff4f8a00695ab64e9cdcdbefac3f53d50ab7bbec785b657e44a12b808a0e82f437da36e4c0ca35360b779982d5df99f28320653e81ab2fa8dda5c8da1b

test:
  secret_key_base: 4082cee7d1bd924ef070313b975a2b12c2b3b8397ffff1b51e25d2e42ae35109f5193730b29f51a71b7ab62a1e930fb88ad7f990d18591a2c9d2dce8d3eac223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
